[package]
name = "rand_hc"
version = "0.4.0"
authors = ["The Rand Project Developers"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-random/rngs"
documentation = "https://docs.rs/rand_hc"
homepage = "https://rust-random.github.io/book"
description = """
HC128 random number generator
"""
keywords = ["random", "rng", "hc128"]
categories = ["algorithms", "no-std"]
edition = "2021"
rust-version = "1.63"

[dependencies]
rand_core = "0.9.0"
