[package]
name = "rand_hc"
version = "0.3.2"
authors = ["The Rand Project Developers"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-random/rngs"
documentation = "https://docs.rs/rand_hc"
homepage = "https://rust-random.github.io/book"
description = """
HC128 random number generator
"""
keywords = ["random", "rng", "hc128"]
categories = ["algorithms", "no-std"]
edition.workspace = true
rust-version.workspace = true

[dependencies]
rand_core = "0.6"
